### ISSUE TITLE
Esmy: Styled component in main file

### ISSUE THREAD

**Issue by SD3K** [The-Jonas-Brothers/fec#34]
Is there a reason for styling creating styled components outside of the /style folder? For consistent code across the project you may want to move these styles to the /style folder.

https://github.com/The-Jonas-Brothers/fec/blob/b040fa97cfc455613aef232bcd2150d34e1566be/client/src/components/Reviews/Ratings.jsx#L8-L18

https://github.com/The-Jonas-Brothers/fec/blob/cc20bb87cd7ad695d247a73cd9804b02ed703842/client/src/components/Reviews/Review.jsx#L7-L18

https://github.com/The-Jonas-Brothers/fec/blob/cc20bb87cd7ad695d247a73cd9804b02ed703842/client/src/components/Reviews/Reviews.jsx#L6-L68

https://github.com/The-Jonas-Brothers/fec/blob/cc20bb87cd7ad695d247a73cd9804b02ed703842/client/src/components/Reviews/ratingComponents/CharacteristicBar.jsx#L7-L41

https://github.com/The-Jonas-Brothers/fec/blob/cc20bb87cd7ad695d247a73cd9804b02ed703842/client/src/components/Reviews/ratingComponents/RatingBar.jsx#L5-L48

https://github.com/The-Jonas-Brothers/fec/blob/cc20bb87cd7ad695d247a73cd9804b02ed703842/client/src/components/Reviews/ratingComponents/StarRating.jsx#L4-L32

https://github.com/The-Jonas-Brothers/fec/blob/cc20bb87cd7ad695d247a73cd9804b02ed703842/client/src/components/Reviews/ReviewForm/Body.jsx#L4-L11

https://github.com/The-Jonas-Brothers/fec/blob/cc20bb87cd7ad695d247a73cd9804b02ed703842/client/src/components/Reviews/ReviewForm/Star.jsx#L6-L30

https://github.com/The-Jonas-Brothers/fec/blob/cc20bb87cd7ad695d247a73cd9804b02ed703842/client/src/components/Reviews/ReviewForm/Summary.jsx#L4-L7

**Comment by ExYY98** [comment]
I originally styled them separately because It was easier for me to visualize, but I have moved them into a style folder inside the style. Fixed!
