### ISSUE TITLE
Esmy: Inconsistent spacing

### ISSUE THREAD

**Issue by SD3K** [The-Jonas-Brothers/fec#35]
There are a few instances throughout the ratings/reviews section where number of linebreaks between methods/sections of code are given extra spacing. Example: 

https://github.com/The-Jonas-Brothers/fec/blob/cc20bb87cd7ad695d247a73cd9804b02ed703842/client/src/components/Reviews/ReviewForm/Recommend.jsx#L15-L18

Please keep in mind if a person is busy (e.g. a hiring manager going through many candidates a day), their first impression will be on code style. Inconsistent spacing and indentations, poor/absent use of linebreaks, and commented code are immediately noticeable

**Comment by ExYY98** [comment]
Fixed!
